package ie.setu.questledger.models.characters

import ie.setu.questledger.models.inventory.CharacterInventory


data class CharacterModel(
    val id: String = "",
    val email: String = "",
    val name: String = "",
    val characterClass: String = "",
    val subclass: String = "",
    val race: String = "",
    val raceVariant: String = "",
    val background: String = "",
    val level: Int = 1,
    val notes: String = "",
    val imageUri: String = "",
    val strength: Int = 10,
    val dexterity: Int = 10,
    val constitution: Int = 10,
    val intelligence: Int = 10,
    val wisdom: Int = 10,
    val charisma: Int = 10,
    val currentHp: Int = 0,
    val sessionStateVersion: Int = 0,
    val temporaryHp: Int = 0,
    val deathSaveSuccesses: Int = 0,
    val deathSaveFailures: Int = 0,
    val isStable: Boolean = false,
    val usedHitDice: Int = 0,
    val remainingSpellSlotsByLevel: List<Int> = emptyList(),
    val hasInspiration: Boolean = false,
    val featureStateVersion: Int = 0,
    val remainingFeatureUses: Map<String, Int> = emptyMap(),
    val activeFeatureIds: List<String> = emptyList(),
    val armourBonus: Int = 0,
    val shieldBonus: Int = 0,
    val inventory: CharacterInventory = CharacterInventory(),
    val skillProficiencyIds: List<String> = emptyList(),
    val racialSkillProficiencyIds: List<String> = emptyList(),
    val selectedRacialSkillIds: List<String> = emptyList(),
    val racialWeaponProficiencyIds: List<String> = emptyList(),
    val racialArmourProficiencyIds: List<String> = emptyList(),
    val racialToolProficiencyIds: List<String> = emptyList(),
    val racialTraitNames: List<String> = emptyList(),
    val selectedRacialAbilityBonusIds: List<String> = emptyList(),
    val selectedRacialLanguageIds: List<String> = emptyList(),
    val racialSpellIds: List<String> = emptyList(),
    val selectedRacialSpellId: String = "",
    val damageResistanceType: String = "",
    val breathWeaponDamageType: String = "",
    val breathWeaponShape: String = "",
    val breathWeaponSaveAbility: String = "",
    val toolProficiencyIds: List<String> = emptyList(),
    val languages: List<String> = emptyList(),
    val copperPieces: Int = 0,
    val silverPieces: Int = 0,
    val electrumPieces: Int = 0,
    val goldPieces: Int = 0,
    val platinumPieces: Int = 0,
    val backgroundFeatureName: String = "",
    val backgroundFeatureDescription: String = "",
    val personalityTraits: List<String> = emptyList(),
    val ideal: String = "",
    val bond: String = "",
    val flaw: String = "",
    val knownSpellIds: List<String> = emptyList(),
    val preparedSpellIds: List<String> = emptyList(),
    val subclassSpellIds: List<String> = emptyList(),
    val subclassSkillProficiencyIds: List<String> = emptyList(),
    val selectedSubclassChoiceIds: List<String> = emptyList(),
    val advancementSelections: List<CharacterAdvancementSelection> = emptyList()
)
